// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5PlF82Pw7bb25cBEfxcwhGGJv20fTCwg',
    appId: '1:713358762993:web:6cb511dd4ad715fa539a50',
    messagingSenderId: '713358762993',
    projectId: 'ict-connect-firebase',
    authDomain: 'ict-connect-firebase.firebaseapp.com',
    storageBucket: 'ict-connect-firebase.appspot.com',
    measurementId: 'G-BFVQDR5G73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbCILlm6yNQAk5M7ry6586U9_JyPDUBz4',
    appId: '1:713358762993:android:bf45b6352b5d0cbf539a50',
    messagingSenderId: '713358762993',
    projectId: 'ict-connect-firebase',
    storageBucket: 'ict-connect-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdfBezSQuZFPUs8dSLsIKJezrsG9Z3NOE',
    appId: '1:713358762993:ios:0bdcd563b0fe3d13539a50',
    messagingSenderId: '713358762993',
    projectId: 'ict-connect-firebase',
    storageBucket: 'ict-connect-firebase.appspot.com',
    iosBundleId: 'com.example.adminApp',
  );
}
